tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install pyspark
      wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-azure/3.3.3/hadoop-azure-3.3.3.jar
      wget https://repo1.maven.org/maven2/com/microsoft/azure/azure-storage/8.6.6/azure-storage-8.6.6.jar
      wget https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util-ajax/11.0.9/jetty-util-ajax-11.0.9.jar
      wget https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/11.0.9/jetty-util-11.0.9.jar
      cp ./*.jar venv/lib/python3.8/site-packages/pyspark/jars
    command: |
      source venv/bin/activate

ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: false
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false