tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install Django
      pip install pyspark
    command: |
      source venv/bin/activate
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
